"use client";

import { useState } from "react";
import { Menu, X } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogClose } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger, SheetClose } from "@/components/ui/sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import SiteMotion from "@/components/SiteMotion";
import LarHeroBackground from "@/components/LarHeroBackground";
import { lar, eventIsPast } from "@/lib/lar";

const nav = [["O Lar", "sobre"], ["Como ajudar", "doar"], ["Empresas", "empresas"], ["Eventos", "eventos"], ["Transparência", "transparencia"]];
function External({ href, children, className = "text-link" }: { href: string; children: React.ReactNode; className?: string }) {
  return <a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}<span className="sr-only"> (abre em nova aba)</span></a>;
}
export default function Home() {
  const [motionEnabled, setMotionEnabled] = useState(true);
  const [partnerOpen, setPartnerOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [interest, setInterest] = useState("");
  const past = eventIsPast(new Date());
  return <><SiteMotion enabled={motionEnabled} />
    <a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
    <header className="site-header"><div className="wrap header-inner">
      <a href="#inicio" className="brand" aria-label="Lar da Criança Fermino Magnani — início"><img src="/images/logo-lar.jpg" alt="" width="60" height="60" /><span>Lar da Criança<strong>Fermino Magnani</strong></span></a>
      <div className="header-actions"><a className="button button-green header-donate" href="#doar">Quero ajudar</a>
      <Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><button className="menu-toggle" aria-label="Abrir menu de navegação"><span>Menu</span><Menu size={21} aria-hidden="true" /></button></SheetTrigger><SheetContent className="lar-sheet" showCloseButton={false} aria-describedby={undefined}><SheetClose asChild><button className="close-button" aria-label="Fechar menu"><X size={23} /></button></SheetClose><SheetHeader><p className="eyebrow">Lar da Criança Fermino Magnani</p><SheetTitle>Chegue mais.</SheetTitle></SheetHeader><nav aria-label="Navegação principal">{[...nav, ["Contato", "contato"]].map(([label, id], index) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}><span className="menu-number">0{index+1}</span>{label}</a>)}</nav><div className="menu-footer"><p>Uma história de cuidado desde 1960.</p><a href="tel:+551433721836">{lar.fixedPhone}</a></div></SheetContent></Sheet></div>
    </div></header>
    <main id="conteudo">
      <section className="hero" id="inicio" aria-labelledby="hero-title">
        <LarHeroBackground enabled={motionEnabled} />
        <div className="hero-shade" aria-hidden="true" />
        <div className="hero-copy wrap"><p className="eyebrow">Desde 1960, fazendo parte de muitas histórias.</p><h1 id="hero-title">Cuidar da infância.<br /><span>Construir o amanhã.</span></h1><p className="lead">Um lugar de cuidado, aprendizado e acolhimento.<br className="desktop-break" /> Uma história que a gente constrói junto.</p><div className="actions"><a href="#doar" className="button hero-primary">Quero fazer parte</a><a href="#sobre" className="button hero-secondary">Conheça o Lar</a></div><p className="hero-note">Lar da Criança Fermino Magnani · Santa Cruz do Rio Pardo</p></div>
      </section>
      <div className="promise-strip"><div className="wrap"><span>Cuidado e acolhimento</span><span>Educação e desenvolvimento</span><span>Comunidade e parceria</span></div></div>
      <section className="section wrap" id="sobre" aria-labelledby="sobre-title"><div className="section-heading"><div><p className="eyebrow">O Lar</p><h2 id="sobre-title">Uma história de cuidado.<br />Todos os dias.</h2></div><p>Nascemos de uma necessidade das famílias: ter um lugar de cuidado para seus filhos enquanto os responsáveis trabalham. Esse vínculo com a comunidade permanece no centro do nosso trabalho.</p></div><div className="about-grid"><div className="history-card"><p className="eyebrow">Nossa história</p><div className="history-year">1960</div><h3>O começo de um compromisso</h3><p>Fundado em Santa Cruz do Rio Pardo, o Lar iniciou efetivamente suas atividades em 1963. Ao longo dessa trajetória, a ampliação do berçário e a formação dos profissionais fizeram parte do seu desenvolvimento.</p><span className="small-label">História registrada na entrevista com a instituição</span></div><div className="care-list">{[["Educação e convivência","Um espaço de aprendizagem, brincadeiras e convivência, respeitando a infância."],["Alimentação e cuidados","Alimentação, higiene e atenção às necessidades das crianças durante sua permanência no Lar."],["Apoio às famílias","Cuidado com as crianças e presença na vida das famílias da nossa cidade."]].map(([title,body]) => {return <article key={String(title)}><div><h3>{String(title)}</h3><p>{String(body)}</p></div></article>;})}</div></div></section>
      <section className="donation-section" id="doar" aria-labelledby="doar-title"><div className="wrap donation-grid"><div><p className="eyebrow">Como ajudar</p><h2 id="doar-title">Seu apoio faz parte<br />do nosso dia a dia.</h2><p>As contribuições ajudam a sustentar o trabalho do Lar e a cuidar dos espaços onde a infância acontece. Cada nova parceria amplia essa rede de apoio.</p><a className="text-link" href="#transparencia">Conheça os documentos da instituição</a></div><div className="donation-card"><div className="card-top"><span>Contribua com o Lar</span></div><h3>Doação por Pix</h3><label htmlFor="pix">Chave Pix</label><div className="pix-value" id="pix">{lar.pix}</div><button className="button button-green full" disabled>Copiar chave Pix</button><div className="donation-divider" /><p>Quer conversar sobre outras formas de apoio?</p><a className="text-link" href="tel:+551433721836">{lar.fixedPhone}</a></div></div></section>
      <section className="section wrap partners-section" id="empresas" aria-labelledby="empresas-title"><div className="section-heading"><div><p className="eyebrow">Empresas e parceiros</p><h2 id="empresas-title">Sua empresa pode<br />estar perto dessa causa.</h2></div><p>Uma parceria começa com uma conversa. Queremos conhecer sua empresa e encontrar possibilidades de contribuição que façam sentido para o Lar.</p></div><div className="partner-options">{[["Apoio financeiro","Converse sobre como contribuir para a manutenção e as necessidades da instituição."],["Produtos e serviços","Apresente o que sua empresa pode oferecer e consulte as necessidades do Lar."],["Projetos e eventos","Demonstre interesse em apoiar iniciativas e encontros em benefício da instituição."]].map(([title,body], i)=>{return <div key={String(title)} className="partner-card"><span className="option-number">0{i+1}</span><h3>{String(title)}</h3><p>{String(body)}</p></div>;})}</div><div className="partner-cta"><div><h3>Vamos construir essa parceria?</h3><p>Conte como sua empresa gostaria de participar.</p></div><button className="button button-green" onClick={()=>setPartnerOpen(true)}>Quero ser parceiro</button></div></section>
      <section className="events-section" id="eventos" aria-labelledby="eventos-title"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">Eventos</p><h2 id="eventos-title">Encontros que aproximam.<br />Apoio que permanece.</h2></div><External href={lar.instagram}>Acompanhe no Instagram</External></div><article className="featured-event"><div className="event-date"><span>SET</span><strong>11</strong><span>2026</span></div><div className="event-info"><span className="badge">{past ? "Evento histórico · anúncio publicado" : "Próximo evento"}</span><h3>Palestra com Mário Sérgio Cortella</h3><p>O sentimento de quem educa nos dias de hoje e a relação escola–família.</p><div className="event-details"><span>20h</span><span>Palácio da Cultura</span><span>Ingresso anunciado: R$ 100,00</span></div><p className="event-address">Rua Conselheiro Antônio Prado, 560 · Centro · Santa Cruz do Rio Pardo</p><External href={lar.cortellaPost}>Ver anúncio e informações do evento</External><p className="event-footnote">Em prol do Lar. Dados do cartaz publicado em 16/07/2026. Consulte a publicação para informações sobre ingressos.</p></div></article><div className="history-heading"><h3>Registros da nossa história</h3><span>Eventos e encontros já registrados</span></div><div className="event-history"><article><span className="badge badge-light">Registro histórico · 2026</span><h3>Formação Lei Lucas</h3><p>Registro de formação em parceria com a Prefeitura de Santa Cruz do Rio Pardo.</p><span className="published">Publicação de 23 de julho de 2026</span><External href={lar.trainingPost}>Ver publicação</External></article><article><span className="badge badge-light">Registro histórico · 2025</span><h3>Festa Junina</h3><p>Memórias reunidas no destaque “festa junina 25” do Instagram da instituição.</p><span className="published">Ano indicado no destaque oficial</span><External href={lar.junina2025}>Ver destaque</External></article><article><span className="badge badge-light">Registro histórico · 2024</span><h3>Festa Junina</h3><p>Registros preservados no destaque “festa junina 24” do Instagram da instituição.</p><span className="published">Ano indicado no destaque oficial</span><External href={lar.junina2024}>Ver destaque</External></article></div></div></section>
      <section className="section wrap transparency-grid" id="transparencia" aria-labelledby="transparencia-title"><div><p className="eyebrow">Transparência</p><h2 id="transparencia-title">Confiança se constrói<br />com informação.</h2><p>Consulte os documentos públicos do Lar da Criança Fermino Magnani no portal de Terceiro Setor da Prefeitura de Santa Cruz do Rio Pardo.</p><External href={lar.transparency} className="button button-outline">Acessar portal da Prefeitura</External><p className="cnpj">CNPJ {lar.cnpj}</p></div><Accordion type="single" collapsible className="documents">{[["parcerias","Parcerias e planos de trabalho","Consulte os termos de colaboração e os planos de trabalho disponíveis na página da instituição."],["contas","Prestação de contas","Acesse os demonstrativos de receitas e despesas e os documentos de prestação de contas disponibilizados pelo município."],["monitoramento","Monitoramento e relatórios","Confira os relatórios e documentos de acompanhamento das parcerias publicados no portal municipal."]].map(([id,title,desc])=><AccordionItem key={id} value={id}><AccordionTrigger className="doc-trigger"><span>{title}</span></AccordionTrigger><AccordionContent className="doc-content"><p>{desc}</p><External href={lar.transparency}>Consultar documentos na fonte</External></AccordionContent></AccordionItem>)}</Accordion></section>
      <section className="contact-section" id="contato" aria-labelledby="contato-title"><div className="wrap contact-grid"><div><p className="eyebrow">Vamos conversar</p><h2 id="contato-title">O Lar está<br />de portas abertas<br /><span>para novas parcerias.</span></h2><p>Conheça nosso trabalho e converse sobre como ajudar.</p></div><address><div><p><strong>Nosso endereço</strong>Rua Albino Trevisan, 115 · Vila Oitenta<br />Santa Cruz do Rio Pardo · SP</p></div><div><p><strong>Telefone</strong><a href="tel:+551433721836">{lar.fixedPhone}</a></p></div><div className="pending-contacts"><p><strong>WhatsApp</strong>{lar.mobilePhone}</p><button className="button button-outline" disabled>Conversar pelo WhatsApp</button><p><strong>E-mail</strong>{lar.email}</p></div></address></div></section>
    </main>
    <footer><div className="wrap footer-main"><a className="brand" href="#inicio"><img src="/images/logo-lar.jpg" alt="" width="52" height="52" /><span>Lar da Criança<strong>Fermino Magnani</strong></span></a><p>Cuidar da infância é um compromisso de todos nós.</p><div className="social-links"><External href={lar.instagram}>Instagram</External><External href={lar.facebook}>Facebook</External></div></div><div className="wrap footer-bottom"><span>Lar da Criança Fermino Magnani · CNPJ {lar.cnpj}</span><a href="#contato">Fale com o Lar</a></div><div className="wrap"><button className="motion-toggle" onClick={() => setMotionEnabled(value => !value)} aria-pressed={motionEnabled}>{motionEnabled ? "Pausar animações" : "Ativar animações"}</button></div></footer>
    <Dialog open={partnerOpen} onOpenChange={setPartnerOpen}><DialogContent className="partner-dialog" showCloseButton={false}><DialogClose asChild><button className="close-button" aria-label="Fechar formulário"><X size={20} /></button></DialogClose><DialogHeader><p className="eyebrow">Empresas e parceiros</p><DialogTitle className="form-title">Vamos conversar sobre parceria.</DialogTitle><DialogDescription>Conte um pouco sobre sua empresa e como gostaria de apoiar o Lar.</DialogDescription></DialogHeader><form onSubmit={e=>e.preventDefault()} className="partner-form"><div className="form-grid"><label>Nome<input name="name" autoComplete="name" required maxLength={120} /></label><label>Empresa<input name="company" autoComplete="organization" required maxLength={160} /></label><label>Cargo<input name="role" autoComplete="organization-title" maxLength={100} /></label><label>E-mail<input type="email" name="email" autoComplete="email" required maxLength={180} /></label><label>Telefone<input type="tel" name="phone" autoComplete="tel" required maxLength={30} /></label><div className="field"><label htmlFor="interesse">Interesse na parceria</label><Select value={interest} onValueChange={setInterest}><SelectTrigger id="interesse" className="interest-select"><SelectValue placeholder="Selecione uma opção" /></SelectTrigger><SelectContent><SelectItem value="financeiro">Apoio financeiro</SelectItem><SelectItem value="produtos">Produtos ou serviços</SelectItem><SelectItem value="eventos">Projetos ou eventos</SelectItem><SelectItem value="outro">Outra possibilidade</SelectItem></SelectContent></Select></div></div><label>Mensagem<textarea name="message" rows={3} maxLength={3000} /></label><button className="button button-green full" type="submit" disabled>Enviar interesse</button></form></DialogContent></Dialog>
  </>;
}
