"use client";

import { useState } from "react";
import { Menu, X } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogClose } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger, SheetClose } from "@/components/ui/sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import CinematicThemeSwitcher from "@/components/ui/cinematic-theme-switcher";
import LarGallery from "@/components/LarGallery";
import SiteMotion from "@/components/SiteMotion";
import LarHeroBackground from "@/components/LarHeroBackground";
import EventCarousel from "@/components/EventCarousel";
import { lar } from "@/lib/lar";

const nav = [["O Lar", "sobre"], ["Como ajudar", "doar"], ["Empresas", "empresas"], ["Eventos", "eventos"], ["Transparência", "transparencia"]];
function External({ href, children, className = "text-link" }: { href: string; children: React.ReactNode; className?: string }) {
  return <a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}<span className="sr-only"> (abre em nova aba)</span></a>;
}
export default function Home() {
  const [motionEnabled, setMotionEnabled] = useState(true);
  const [partnerOpen, setPartnerOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [interest, setInterest] = useState("");

  return <><SiteMotion enabled={motionEnabled} />
    <a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
    <header className="site-header"><div className="wrap header-inner">
      <a href="#inicio" className="brand" aria-label="Lar da Criança Fermino Magnani — início"><img src="/images/logo-lar.jpg" alt="" width="60" height="60" /><span>Lar da Criança<strong>Fermino Magnani</strong></span></a>
      <div className="header-actions"><a className="button button-green header-donate" href="#doar">Quero ajudar</a>
      <Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><button className="menu-toggle" aria-label="Abrir menu de navegação"><span>Menu</span><Menu size={21} aria-hidden="true" /></button></SheetTrigger><SheetContent className="lar-sheet" showCloseButton={false} aria-describedby={undefined}><SheetClose asChild><button className="close-button" aria-label="Fechar menu"><X size={23} /></button></SheetClose><SheetHeader><p className="eyebrow">Lar da Criança Fermino Magnani</p><SheetTitle>Chegue mais.</SheetTitle></SheetHeader><nav aria-label="Navegação principal">{[...nav, ["Contato", "contato"]].map(([label, id], index) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}><span className="menu-number">0{index+1}</span>{label}</a>)}</nav><div className="menu-theme"><span>Tema escuro</span><CinematicThemeSwitcher motionEnabled={motionEnabled} /></div><div className="menu-footer"><p>Uma história de cuidado desde 1960.</p><a href="tel:+551433721836">{lar.fixedPhone}</a></div></SheetContent></Sheet></div>
    </div></header>
    <main id="conteudo">
      <section className="hero" id="inicio" aria-labelledby="hero-title">
        <LarHeroBackground enabled={motionEnabled} />
        <div className="hero-shade" aria-hidden="true" />
        <div className="hero-copy wrap"><p className="eyebrow">Desde 1960, fazendo parte de muitas histórias.</p><h1 id="hero-title">Cuidar da infância.<br /><span>Construir o amanhã.</span></h1><p className="lead">Um lugar de cuidado, aprendizado e acolhimento.<br className="desktop-break" /> Uma história que a gente constrói junto.</p><div className="actions"><a href="#doar" className="button hero-primary">Quero fazer parte</a><a href="#sobre" className="button hero-secondary">Conheça o Lar</a></div><p className="hero-note">Lar da Criança Fermino Magnani · Santa Cruz do Rio Pardo</p></div>
      </section>
      <div className="promise-strip"><div className="wrap"><span>Cuidado e acolhimento</span><span>Educação e desenvolvimento</span><span>Comunidade e parceria</span></div></div>
      <section className="section wrap" id="sobre" aria-labelledby="sobre-title"><div className="section-heading"><div><p className="eyebrow">O Lar</p><h2 id="sobre-title">Cuidado que atravessa gerações.</h2></div><p>Acolhimento e educação para a infância, junto às famílias de Santa Cruz do Rio Pardo.</p></div><div className="about-grid"><div className="history-card"><p className="eyebrow">Nossa história</p><div className="history-year">1960</div><h3>Nossa história começa aqui</h3><p>Fundado em 1960, o Lar iniciou suas atividades em 1963 e cresceu junto à comunidade.</p></div><div className="care-list">{[["Educação e convivência","Aprender, brincar e conviver."],["Alimentação e cuidados","Atenção às necessidades de cada criança."],["Apoio às famílias","Uma presença de confiança no dia a dia."]].map(([title,body]) => {return <article key={String(title)}><div><h3>{String(title)}</h3><p>{String(body)}</p></div></article>;})}</div></div></section>
      <LarGallery motionEnabled={motionEnabled} />
      <section className="donation-section" id="doar" aria-labelledby="doar-title"><div className="wrap donation-grid"><div><p className="eyebrow">Como ajudar</p><h2 id="doar-title">Faça parte desse cuidado.</h2><p>Sua contribuição ajuda a manter os cuidados e os espaços do Lar.</p><a className="text-link" href="#transparencia">Consulte nossa transparência</a></div><div className="donation-card"><h3>Doação por Pix</h3><label htmlFor="pix">Chave Pix</label><div className="pix-value" id="pix">{lar.pix}</div><button className="button button-green full" disabled>Copiar chave Pix</button><div className="donation-divider" /><p>Outras formas de ajudar</p><a className="text-link" href="tel:+551433721836">{lar.fixedPhone}</a></div></div></section>
      <section className="section wrap partners-section" id="empresas" aria-labelledby="empresas-title"><div className="section-heading"><div><p className="eyebrow">Empresas e parceiros</p><h2 id="empresas-title">Sua empresa, junto do Lar.</h2></div><p>Encontre uma forma de contribuir com a nossa história.</p></div><div className="partner-options">{[["Apoio financeiro","Ajude a manter o trabalho do Lar."],["Produtos e serviços","Compartilhe o que sua empresa pode oferecer."],["Projetos e eventos","Apoie iniciativas em benefício do Lar."]].map(([title,body], i)=>{return <div key={String(title)} className="partner-card"><span className="option-number">0{i+1}</span><h3>{String(title)}</h3><p>{String(body)}</p></div>;})}</div><div className="partner-cta"><div><p>Uma parceria começa com uma conversa.</p></div><button className="button button-green" onClick={()=>setPartnerOpen(true)}>Quero ser parceiro</button></div></section>
      <EventCarousel />
      <section className="section wrap transparency-grid" id="transparencia" aria-labelledby="transparencia-title"><div><p className="eyebrow">Transparência</p><h2 id="transparencia-title">Transparência em cada passo.</h2><p>Documentos e prestações de contas disponíveis no portal da Prefeitura.</p><External href={lar.transparency} className="button button-outline">Acessar portal da Prefeitura</External></div><Accordion type="single" collapsible className="documents">{[["parcerias","Parcerias e planos de trabalho","Consulte os termos de colaboração e os planos de trabalho disponíveis na página da instituição."],["contas","Prestação de contas","Acesse os demonstrativos de receitas e despesas e os documentos de prestação de contas disponibilizados pelo município."],["monitoramento","Monitoramento e relatórios","Confira os relatórios e documentos de acompanhamento das parcerias publicados no portal municipal."]].map(([id,title,desc])=><AccordionItem key={id} value={id}><AccordionTrigger className="doc-trigger"><span>{title}</span></AccordionTrigger><AccordionContent className="doc-content"><p>{desc}</p><External href={lar.transparency}>Consultar documentos na fonte</External></AccordionContent></AccordionItem>)}</Accordion></section>
      <section className="contact-section" id="contato" aria-labelledby="contato-title"><div className="wrap contact-grid"><div><p className="eyebrow">Vamos conversar</p><h2 id="contato-title">Vamos conversar?</h2><p>Estamos por aqui para ouvir você.</p></div><address><div><p><strong>Nosso endereço</strong>Rua Albino Trevisan, 115 · Vila Oitenta<br />Santa Cruz do Rio Pardo · SP</p></div><div><p><strong>Telefone</strong><a href="tel:+551433721836">{lar.fixedPhone}</a></p></div><div className="pending-contacts"><p><strong>WhatsApp</strong>{lar.mobilePhone}</p><button className="button button-outline" disabled>Conversar pelo WhatsApp</button><p><strong>E-mail</strong>{lar.email}</p></div></address></div></section>
    </main>
    <footer><div className="wrap footer-main"><a className="brand" href="#inicio"><img src="/images/logo-lar.jpg" alt="" width="52" height="52" /><span>Lar da Criança<strong>Fermino Magnani</strong></span></a><p>Cuidar da infância é um compromisso de todos nós.</p><div className="social-links"><External href={lar.instagram}>Instagram</External><External href={lar.facebook}>Facebook</External></div></div><div className="wrap footer-bottom"><span>Lar da Criança Fermino Magnani · CNPJ {lar.cnpj}</span><a href="#contato">Fale com o Lar</a></div><div className="wrap"><button className="motion-toggle" onClick={() => setMotionEnabled(value => !value)} aria-pressed={motionEnabled}>{motionEnabled ? "Pausar animações" : "Ativar animações"}</button></div><div className="wrap"><details className="image-credits"><summary>Créditos de imagem</summary><p>Retrato de Mário Sérgio Cortella: <External href="https://commons.wikimedia.org/wiki/File:Mario_Sergio_Cortella.jpg">Multishow</External> · <External href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</External>.</p></details></div></footer>
    <Dialog open={partnerOpen} onOpenChange={setPartnerOpen}><DialogContent className="partner-dialog" showCloseButton={false}><DialogClose asChild><button className="close-button" aria-label="Fechar formulário"><X size={20} /></button></DialogClose><DialogHeader><p className="eyebrow">Empresas e parceiros</p><DialogTitle className="form-title">Vamos conversar sobre parceria.</DialogTitle><DialogDescription>Conte um pouco sobre sua empresa e como gostaria de apoiar o Lar.</DialogDescription></DialogHeader><form onSubmit={e=>e.preventDefault()} className="partner-form"><div className="form-grid"><label>Nome<input name="name" autoComplete="name" required maxLength={120} /></label><label>Empresa<input name="company" autoComplete="organization" required maxLength={160} /></label><label>Cargo<input name="role" autoComplete="organization-title" maxLength={100} /></label><label>E-mail<input type="email" name="email" autoComplete="email" required maxLength={180} /></label><label>Telefone<input type="tel" name="phone" autoComplete="tel" required maxLength={30} /></label><div className="field"><label htmlFor="interesse">Interesse na parceria</label><Select value={interest} onValueChange={setInterest}><SelectTrigger id="interesse" className="interest-select"><SelectValue placeholder="Selecione uma opção" /></SelectTrigger><SelectContent><SelectItem value="financeiro">Apoio financeiro</SelectItem><SelectItem value="produtos">Produtos ou serviços</SelectItem><SelectItem value="eventos">Projetos ou eventos</SelectItem><SelectItem value="outro">Outra possibilidade</SelectItem></SelectContent></Select></div></div><label>Mensagem<textarea name="message" rows={3} maxLength={3000} /></label><button className="button button-green full" type="submit" disabled>Enviar interesse</button></form></DialogContent></Dialog>
  </>;
}
